FIX: Resolve load-time ReferenceError under exotic loaders
In v1.0.5, the shift to chunks introduced an import cycle between the
"internal" chunk and the "options" chunk. Under common usage, this isn't
a problem, as Node's ESM loader handles it well. When using some
transformations (such as OpenTelemetry), this cycle can cause errors at
load time:

>    node_modules/temporal-polyfill/chunks/options.js:65
>    const roundingModeFuncs = [ Math.floor, roundHalfFloor, Math.ceil, ... ];
>                                            ^
>    ReferenceError: Cannot access 'roundHalfFloor' before initialization
>        at ModuleJob.run (node:internal/modules/esm/module_job:561:25)

To resolve, I've split a new "internal-base" chunk out of the "internal"
chunk. This new chunk can be safely imported by both the "internal" and
"options" chunks without any cycles forming.

Resolves: https://github.com/fullcalendar/temporal-polyfill/issues/107